import type { Metadata } from "next";
import { Mali } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./(frontend)/SessionProviderWrapper";

const mali = Mali({
  variable: "--font-mali",
  subsets: ["latin", "thai"], // ต้องมี "thai" เพื่อรองรับภาษาไทย
  weight: ["400", "500", "700"], // เลือกน้ำหนักตามต้องการ
});

export const metadata: Metadata = {
  title: "HomePaw แจ้งพบสัตว์ไร้บ้าน",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="th">
      <body className={`${mali.variable} font-mali antialiased`}>
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
